export const products = [
  {
    _id: '621235e59540445b3sdfe9s0',
    name: 'GLOW GODDESS',
    image: 'https://files.myglamm.com/site-images/800x800/5-spotlight-chisel-it-copy-1-2.png',
    description:
      "5 in 1 Primer-Concealer-Foundation-Compact with SPF 30 & Skin Tone Corrector Palette",
    brand: 'Maybeline',
    category: 'Makeup',
    price: 599.99,
    rating: 5,
    numReviews: 1,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '636985e59540445b3c45e6af',
    name: 'POPXO SHEET MASK',
    image: 'https://files.myglamm.com/site-images/800x800/SD1.png',
    description:
      'Sheet Mask For EOD Skincare',
      brand: 'Lakmea',
    category: 'Skin Care',
    price: 929.99,
    rating: 3,
    numReviews: 1,
    isNew: false,

    reviews: [],
    stock: 0,
  },
  {
    _id: '6369860d9540445b3c45e6b1',
    name: 'MYGLAMM HAIR MASK',
    image: 'https://files.myglamm.com/site-images/800x800/Mangosteen---Avocado-Hair-Mask-1_2.jpg',
    description:
      "Strengthening & Repairing Hair Mask with extracts from natural superfoods",
    brand: 'Bellavita',
    category: 'Hair Care',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 0,
    isNew: false,

    reviews: [],
    stock: 8,
  },
  {
    _id: '6369863c9540445b3c45e6b3',
    name: 'EYESHADOW PALETTE',
    image: 'https://files.myglamm.com/site-images/800x800/PopXo-eyeshadow-kit-1200x1200.jpg',
    description:
      'Compact Eyeshadow Palette with 9 shades in Matte, Metallic & Foil Finishes',
    brand: 'Lakmea',
    category: 'Make Up',
    price: 599.99,
    rating: 5,
    numReviews: 0,
    isNew: false,

    reviews: [],
    stock: 7,
  },
  {
    _id: '636986579540445b3c45e6b5',
    name: 'CREAMY MATTE LIPSTICK',
    image: 'https://files.myglamm.com/site-images/800x800/Lit21.jpg',
    description:
      " Perfect Matte Slimstick",
    brand: 'Maybeline',
    category: 'Makeup',
    price: 600,
    rating: 4,
    numReviews: 1,
    isNew: true,

    reviews: [],
    stock: 1,
  },
  {
    _id: '636986749540445b3c45e6b7',
    name: 'SUNSCREAM',
    image: 'https://files.myglamm.com/site-images/800x800/SN4.png',
    description:'Lotion For Sun-bathers',

    brand: 'Lakmea',
    category: 'Skin Care',
    price: 335,
    rating: 5,
    numReviews: 4,
    isNew: false,
    stock: 0,
  },
  {
    _id: '63804a5079636c2ced47757d',
    name: ' AMLA HAIR OIL ',
    image: 'https://files.myglamm.com/site-images/800x800/3637a530-1fb9-11ec-9956-f11381c8bb2c1.jpg',
    brand: 'Lakmea',
    category: 'Hair Care',
    description:
      'Prevents damage & Improves overall Hair Health',
    numReviews: 2,
    price: 699,
    stock: 5,
    isNew: true,
    reviews: [],
  },
  {
    _id: '6381275e8e8648e00b7c82f7',
    name: 'SUPERFOODS DAMAGE  DUO',
    image: 'https://files.myglamm.com/site-images/800x800/SF--Damage-Repair.jpg',
    brand: 'Purple',
    category: 'Skin Care',
    description:
      'Nourishing & Hydrating Combo With Extracts From Natural Superfoods',
    rating: 3,
    numReviews: 12,
    price: 449,
    stock: 34,
    isNew: true,
    reviews: [],
  },
  {
    _id: '63895d3b2a3e062504353082',
    name: ' Eyliner Mascara',
    image: 'https://files.myglamm.com/site-images/800x800/jademasc.jpg',
    brand: 'Manish MAlhotra',
    category: 'Makeup',
    description:
      'Beauty Essential Eye Kit',
      rating: 4,
    numReviews: 12,
    price: 422.99,
    stock: 33,
    isNew: false,
    reviews: [],
  },

  {
    _id: '63895d3b2a3e062504353032',
    name: ' NOURISHING BODY CLEANSER',
    image: 'https://files.myglamm.com/site-images/800x800/Watermelon---Aloe-Body-Wash-1_1.jpg',
    brand: 'Manish MAlhotra',
    category: 'Makeup',
    description:
      'Ultra Nourishing Body Cleanser for sensitive',
      rating: 4,
    numReviews: 14,
    price: 529.99,
    stock: 12,
    isNew: false,
    reviews: [],
  },

  {
    _id: '63895d3b2a3e062504353022',
    name: ' NAIL KIT',
    image: 'https://files.myglamm.com/site-images/800x800/CHii_2.jpg',
    brand: 'Manish MAlhotra',
    category: 'Makeup',
    description:
      'Mini Nail Polish',
      rating: 4,
    numReviews: 12,
    price: 499.99,
    stock: 38,
    isNew: false,
    reviews: [],
  },

  {
    _id: '63895d3b2a3e062504353028',
    name: 'SETTING POWDER',
    image: 'https://files.myglamm.com/site-images/800x800/PSB1.jpg',
    brand: 'Manish MAlhotra',
    category: 'Makeup',
    description:
      ' Essential Setting Powder',
      rating: 4,
    numReviews: 12,
    price: 899.99,
    stock: 15,
    isNew: true,
    reviews: [],
  },
];
